### PR TITLE
rename to jsx

### PR DESCRIPTION
**Pull request by Hoten**
#41

### CODE REVIEW

**Comment by dudko** [comment]
Hello @Hoten ,

have you tried to configure webpack to resolve the extension? Have a look at [resolve.extensions](https://webpack.js.org/configuration/resolve/#resolve-extensions) or [github issue](https://github.com/webpack/webpack/issues/231) discussing it in greater details.

Let me know how it goes. :)

**Comment by Hoten** [comment]
I don't follow. My webpack is configured fine - it parses JS as JS, and JSX as JSX. However, this file is a .js file but is actually JSX.

**Comment by dudko** [comment]
@Hoten , isn't then enough to change the file extensions form `.js` to `.jsx`? The changes you have done to `import` statements are redundant. For example this one:

```js
import createMathComponent from './createMathComponent.jsx';
```

**Comment by Hoten** [comment]
Oh, in the PR! I misunderstood and throught you meant in my own code. Let
me give that a shot.

**Comment by dudko** [comment]
@Hoten , any updates? Thanks.

**Comment by Hoten** [comment]
I do not know how to get rollup to look for .jsx extension during module resolution step - I get this error when building w/o those changes in the imports:

```
Could not resolve './InlineMath' from src/index.js
```

Changing the import to include the extension resolved that issue.

**Comment by dudko** [comment]
@Hoten , try to install [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve)  as dev dependency and update `rollup.config.js` to:

```js
import resolve from 'rollup-plugin-node-resolve';

const minify = !!process.env.MINIFY;

const plugins = [resolve({ extensions: ['.js', '.jsx'] }), babel()];
```

**Comment by Hoten** [comment]
I tried that package before, must have done something terribly wrong because it didn't work my first attempt. Works now though. Thanks!

**Comment by Hoten** [comment]
Closing to remove from my PR list.

**Pull request closed without merging**
