### PR TITLE
Do not publish .babelrc

### PR DESCRIPTION
**Pull request by Hoten**
A published `.babelrc` file creates issues with babel's "lookup behavior": https://stackoverflow.com/questions/43727228/ignore-babelrc-relative-to-a-node-module

Errors look like this: https://github.com/rollup/rollup-plugin-node-resolve/issues/27

The particular error I get is:

```
  Error: ./node_modules/react-katex/src/index.js
  Module build failed: Error: Couldn't find preset "es2015-rollup" relative to directory "/var/www/current/var/@coursehero-components/study-guides/node_modules/react-katex"
  at /var/www/current/var/@coursehero-components/study-guides/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
  at Array.map (<anonymous>)
  at OptionManager.resolvePresets (/var/www/current/var/@coursehero-components/study-guides/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
  at OptionManager.mergePresets (/var/www/current/var/@coursehero-components/study-guides/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
  at OptionManager.mergeOptions (/var/www/current/var/@coursehero-components/study-guides/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
  at OptionManager.init (/var/www/current/var/@coursehero-components/study-guides/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
  at File.initOptions (/var/www/current/var/@coursehero-components/study-guides/node_modules/babel-core/lib/transformation/file/index.js:212:65)
  at new File (/var/www/current/var/@coursehero-components/study-guides/node_modules/babel-core/lib/transformation/file/index.js:135:24)
  at Pipeline.transform (/var/www/current/var/@coursehero-components/study-guides/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
  at transpile (/var/www/current/var/@coursehero-components/study-guides/node_modules/babel-loader/lib/index.js:50:20)
  at Object.module.exports (/var/www/current/var/@coursehero-components/study-guides/node_modules/babel-loader/lib/index.js:175:20)
```

### CODE REVIEW

**Comment by talyssonoc** [comment]
Hello @Hoten! Thanks for the contribution, I agree that this needs to be done. Looks like the build is breaking, could you check the reason?

**Comment by Hoten** [comment]
I don't see how this could be related to this change.

https://travis-ci.org/talyssonoc/react-katex/jobs/344475864

**Comment by Hoten** [comment]
The other open, pending PRs have the same error in the same Travis job. It seems your CI is not working as you expect.

**Comment by dudko** [comment]
@Hoten , I fixed the build issue travis-ci. I wasn't realted to `.babelrc`. Check #35.

Could you please give me more details about how did you run into your issue? Node and npm versions as well the commands you used. Thanks!

**Comment by dudko** [comment]
@Hoten , closing this PR. Please, submit new issue if you encounter problems with `rollup` and `.babelrc`.

**Pull request closed without merging**
